<a href="https://colab.research.google.com/github/yjin0034/TIL-1/blob/master/2-1.%20%EB%B0%B0%EC%97%B4%EC%9D%98%20index%20%EC%A0%91%EA%B7%BC%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 2. N차원 배열의 인덱싱

## 2-1. 배열의 index 접근하기

### 배열의 인덱싱

In [4]:
# 1차원 배열 인덱싱

# 0~9 사이의 숫자를 가진 1차원 배열 생성
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# 또는, arr = np.arange(10) 로 0~9 사이의 숫자를 가진 1차원 배열 생성

print(arr)

print(arr[3])     # 인덱스 3번째에 위치한 데이터, 3 출력.  0부터 시작해서 3번째 값 2 아니다. 그냥 있는 그대로 3번째 값 3이다.

print(arr[1])     # 인덱스 1번째에 위치한 데이터, 1 출력

#print(arr[10])    # 해당 배열에 10번째 인덱스는 존재하지 않는다. 에러 발생

print(arr[-1])    # 맨 끝에서부터 첫 번째에 해당하는 데이터, 9 출력

print(arr[-3])    # 맨 끝에서부터 세 번째에 해당하는 데이터, 7 출력

print(arr[-10])   # 맨 끝에서부터 10번째에 해당하는 데이터, 0 출력

[0 1 2 3 4 5 6 7 8 9]
3
1
9
7
0


In [10]:
# 2차원 배열 인덱싱

# 3×4 행렬의 2차원 배열 생성
arr = np.array([[1, 2, 3, 4,],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr)

print()

print(arr.shape, arr.ndim)       # (3, 4) : 3×4 행렬  # 2 : 2차원

print()

print(arr[0][2])                 # 0번째 행에 대해서, 2번째 열에 해당하는 값, 3 출력

print(arr[0, 2])                 # 위 코드와 같은 결과값 출력  # 0번째 행에서 2번째 열에 해당하는 값, 3 출력

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

(3, 4) 2

3
3


### 배열의 슬라이싱

In [16]:
# 1차원 배열의 슬라이싱

# 0~9 사이의 숫자를 가진 1차원 배열 생성
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[2:9])           # 2번째 값부터 시작해 9번째 미만까지의 값들 출력. [2 3 4 5 6 7 8]

print(arr[3:])            # 3번째 값부터 시작해 끝까지 출력. [3 4 5 6 7 8 9]

print(arr[:5])            # 처음부터 시작해 5번째 미만까지의 값들 출력. [0 1 2 3 4]

print(arr[:-1])           # 처음부터 시작해, 맨 끝에서부터 첫 번째에 해당하는 데이터인 9미만까지의 값들 출력. [0 1 2 3 4 5 6 7 8] 

[2 3 4 5 6 7 8]
[3 4 5 6 7 8 9]
[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8]


In [22]:
# 2차원 배열의 슬라이싱

# 3×4 행렬의 2차원 배열 생성
arr = np.array([[1, 2, 3, 4,],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr[0, :])          # 0번째 행에 대해서, 모든 값 출력. [:]은 처음부터 끝까지의 모든 값을 의미. [1 2 3 4]

print(arr[:, 2])          # 모든 행에 대해서, 2번째 열에 해당하는 값(들) 출력. [3 7 11]

print()

print(arr[:3, :])         # 모든 행에 대해서([:3, ] : 행의 처음부터 3번째 미만까지의 행), 모든 열에 해당하는 값([:]) 출력. 즉, 배열의 모든 원소들 출력

print()

print(arr[:2, 2:])        # 2번째까지의 행에 대해서, 2~3번째 열에 해당하는 값들 출력. [:2, ] : 처음부터 시작해, 2번째 미만까지의 행. [ , 2:] : 2번째부터 시작해 끝까지에 해당하는 열

[1 2 3 4]
[ 3  7 11]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[3 4]
 [7 8]]


>**참조**
>
>인프런 : 데이터 과학을 위한 파이썬 NumPy Basic
>
>https://www.inflearn.com/course/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B3%BC%ED%95%99-%EB%84%98%ED%8C%8C%EC%9D%B4-%EA%B8%B0%EB%B3%B8#