<a href="https://colab.research.google.com/github/yjin0034/TIL-1/blob/master/2-2.%20Fancy%20%EC%9D%B8%EB%8D%B1%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 2. N차원 배열의 인덱싱

## 2-2. 배열의 Fancy 인덱싱

특정 인덱스를 여러개 선택하여 탐색하는 방법

In [2]:
# 1차원 배열 Fancy 인덱싱

# 5~30 사이의 5의 배수 숫자를 가진 1차원 배열 생성
arr = np.array([5, 10, 15, 20, 25, 30])

print(arr)

print()

print(arr[[0, 2, 4]])       # arr 1차원 배열의 원소 중 0, 2, 4번째 데이터 출력

[ 5 10 15 20 25 30]

[ 5 15 25]


In [3]:
# 2차원 배열

# 3×4 행렬의 2차원 배열 생성 
arr = np.array([[5, 10, 15, 20],
               [25, 30, 35, 40],
               [45, 50, 55, 60]])

print(arr)

print()

print(arr[[0, 2], 2:])        # arr 2차원 배열의 원소들 중, 0, 2번째 행에 대해서, 2번째부터 끝까지의 열(2~3번째 열)에 해당하는 데이터 출력

print()

print(arr[1:, [2, 3]])        # arr 2차원 배열의 원소들 중, 1번째부터 끝까지의 행(1~2번째 행)에 대해서, 2, 3번째 열에 해당하는 데이터 출력

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]

[[15 20]
 [55 60]]

[[35 40]
 [55 60]]


>**참조**
>
>인프런 : 데이터 과학을 위한 파이썬 NumPy Basic
>
>https://www.inflearn.com/course/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B3%BC%ED%95%99-%EB%84%98%ED%8C%8C%EC%9D%B4-%EA%B8%B0%EB%B3%B8#