<a href="https://colab.research.google.com/github/yjin0034/TIL-1/blob/master/2_3_Boolean_%EC%9D%B8%EB%8D%B1%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 2. N차원 배열의 인덱싱

## 2-3. 배열의 Boolean 인덱싱

특정 조건에 해당하는 선택여부(True, False)로, True에 해당하는 인덱스 위치에 있는 ndarray를 반환하는 인덱싱 방식

* numpy Boolean 인덱싱은 배열 각 요소의 선택여부를 True, False로 표현한다.
* Boolean 값으로 된 배열을 인덱스로 사용하면 대상 배열의 인덱스가 True인 아이템만 결과로 추출할 수 있다.
* 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 한다.


In [2]:
# 1차원 배열 Boolean 인덱싱

# 1~4 사이의 숫자를 가진 1차원 배열 생성
arr = np.array([1, 2, 3, 4])

print(arr[[True, True, False, True]])    # 인덱스 배열의 각 요소의 선택여부 중 선택여부가 True인 요소(들)의 위치에 해당하는, arr 1차원 배열의 요소들만 배열로 반환   # [1 2 4]
                                         # 인덱스 배열의 크기는 대상 배열의 크기와 같아야 한다

[1 2 4]


In [3]:
# 2차원 배열 Boolean 인덱싱

# 2×4 행렬의 2차원 배열 생성
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print(arr[[True, False], True])    # 인덱스 배열의 각 요소의 선택여부 중 선택여부가 True인 요소(들)의 위치에 해당하는, arr 2차원 배열의 요소들만 배열로 반환
                                   # arr 2차원 배열의 원소들 중, 0번째 행에 대해서, 모든 열에 해당하는 데이터 반환   # [[1 2 3 4]]
                                   # 인덱스 배열의 크기는 대상 배열의 크기와 같아야 하지만, 위 코드에서와 같이 열(또는 행) 전체를 한 값인 True(또는 False)로 주는 식의 방식도 가능한가 봄 
                                   #
                                   # 인덱스 배열의 선택여부
                                   # 행 : 0번째 행만 True
                                   # 열 : 모든 열 True

print(arr[[True, False], [True, False, True, False]])    # 인덱스 배열의 각 요소의 선택여부 중 선택여부가 True인 요소(들)의 위치에 해당하는, arr 2차원 배열의 요소들만 배열로 반환
                                   # arr 2차원 배열의 원소들 중, 0번째 행에 대해서, 0, 2번째 열에 해당하는 데이터 반환   # [1 3]
                                   # 인덱스 배열의 크기는 대상 배열의 크기와 같아야 한다
                                   #
                                   # 인덱스 배열의 선택여부
                                   # 행 : 0번째 행만 True
                                   # 열 : 0, 2번째 열 True


[[1 2 3 4]]
[1 3]


## 2-4. 연산자를 활용한 배열 인덱싱

In [4]:
# 비교 연산자, 논리 연산자를 활용한 1차원 배열 인덱싱

# 1~10 사이의 숫자를 가진 1차원 배열 생성
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[arr >= 8])      # 배열의 요소들 중 8보다 크거나 같은 요소들만 배열로 반환   # [8 9 10]

print()

print(arr[(arr != 10) & (arr != 5)])     # 배열의 요소들 중 10과 5에 해당하지 않는 요소들만 배열로 반환   # [1 2 3 4 6 7 8 9]

[ 8  9 10]

[1 2 3 4 6 7 8 9]


In [5]:
# 비교 연산자를 활용한 2차원 배열 인덱싱

# 2×4 행렬의 2차원 배열 생성
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print(arr[arr > 3])       # 배열의 요소들 중 3보다 큰 요소들만 배열로 반환   # [4 5 6 7 8]

print()

print(arr[arr <= 4])      # 배열의 요소들 중 4보다 작거나 같은 요소들만 배열로 반환   # [1 2 3 4]

print()

print(arr[arr % 2 == 0])  # 배열의 요소들 중 2의 배수(2로 나누었을 때 나머지가 0인)에 해당하는 요소들만 배열로 반환   # [2 4 6 8]

[4 5 6 7 8]

[1 2 3 4]

[2 4 6 8]


>**참조**
>
>인프런 : 데이터 과학을 위한 파이썬 NumPy Basic
>
>https://www.inflearn.com/course/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B3%BC%ED%95%99-%EB%84%98%ED%8C%8C%EC%9D%B4-%EA%B8%B0%EB%B3%B8#