<a href="https://colab.research.google.com/github/yjin0034/TIL-1/blob/master/3-1.%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%97%B0%EC%82%B01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 3. N차원 배열 연산법

## 3-1. 배열의 연산1: 사칙연산/제곱/제곱근/몫/나머지

In [2]:
# 3×3 shape의 2차원 배열 2개 생성
arr1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr2 = np.array([[2, 2, 2],
                [2, 2, 2],
                [2, 2, 2]])

print(arr1)

print()

print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [3]:
# 두 배열 간의 덧셈
print(arr1 + arr2)

print()

# np.add() 메서드를 사용한 두 배열 간의 덧셈
print(np.add(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [4]:
# 두 배열 간의 뺄셈
print(arr1 - arr2)

print()

# np.subtract() 메서드를 사용한 두 배열 간의 뺄셈
print(np.subtract(arr1, arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [5]:
# 두 배열 간의 곱셈
print(arr1 * arr2)

print()

# np.multiply() 메서드를 사용한 두 배열 간의 곱셈
print(np.multiply(arr1, arr2))

# 주의할 점: 이 방법들은 행렬 간의 내적(dot product) 연산이 아니다. 그냥 단순히 두 행렬 원소들끼리의 곱셈만을 행하여 계산한 것이다.
# 내적 연산은 다음 파트에서 다룬다

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [6]:
# 두 배열 간의 나눗셈
print(arr1 / arr2)

print()

# np.divide() 메서드를 사용한 두 배열 간의 곱셈
print(np.divide(arr1, arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [7]:
# 배열의 제곱 계산

# 3×3 shape의 2차원 배열 생성
arr3 = np.array([[1, 1, 1],
                [4, 4, 4],
                [9, 9, 9]])

# arr3 배열의 2제곱 계산   # 각 원소들에 2제곱한 값들을 배열로 반환 
print(arr3 ** 2)

print()

# np.square() 메서드를 사용한 배열의 (2)제곱 계산
print(np.square(arr3))

print()

# arr1 배열의 5제곱 계산   # 각 원소들에 5제곱한 값들을 배열로 반환
print(arr3 ** 5)

[[ 1  1  1]
 [16 16 16]
 [81 81 81]]

[[ 1  1  1]
 [16 16 16]
 [81 81 81]]

[[    1     1     1]
 [ 1024  1024  1024]
 [59049 59049 59049]]


In [8]:
# 배열의 제곱근 계산

# arr3 배열의 제곱근 계산   # 각 원소들의 제곱근 값들을 배열로 반환
print(np.sqrt(arr3))

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [9]:
# 배열의 몫 계산

# arr3 배열의 몫 계산   # 각 원소들을 2로 나누었을 때의 몫들을 배열로 반환
print(arr3 // 2)

[[0 0 0]
 [2 2 2]
 [4 4 4]]


In [10]:
# 배열의 나머지 계산

# arr3 배열의 나머지 계산   # 각 원소들을 2로 나누었을 때의 나머지들을 배열로 반환
print(arr3 % 2)

[[1 1 1]
 [0 0 0]
 [1 1 1]]


>**참조**
>
>인프런 : 데이터 과학을 위한 파이썬 NumPy Basic
>
>https://www.inflearn.com/course/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B3%BC%ED%95%99-%EB%84%98%ED%8C%8C%EC%9D%B4-%EA%B8%B0%EB%B3%B8#