<a href="https://colab.research.google.com/github/yjin0034/TIL-1/blob/master/3-2%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%97%B0%EC%82%B02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 3. N차원 배열 연산법

## 3-2. 배열의 연산2: 내적(dot product) / 절댓값 / 올림 / 내림 / 반올림 / 버림

In [2]:
# 두 1차원 배열 간의 내적 연산

# 내적(dot product): 스칼라 곱이라고도 한다
'''
1차원 행렬의 내적 연산: [a, b, c] · [e, f, g]  =  [ae + bf + cg] 
'''

# 1차원 행렬 생성
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 4, 6])

# np.dot() 메서드를 사용한 1차원 배열 간의 내적 연산
print(np.dot(arr1, arr2))

28


In [3]:
# 두 2차원 배열 간의 내적 연산

'''
2차원 행렬의 내적 연산: [[a, b   · [[e, f]   =  [[ae + bg, af + bh] 
                         [c, d]]     [g, h]]      [ce + dg, cf + dh]]
'''

# 2×2 shape의 2차원 배열 생성
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[2, 4],
                 [0, 1]])

# np.dot() 메서드를 사용한 2차원 배열 간의 내적 연산
print(np.dot(arr1, arr2))

[[ 2  6]
 [ 6 16]]


In [4]:
# 배열의 절댓값

# 2×2 shape의 2차원 배열 생성
arr1 = np.array([[2, -3],
                 [-3, 4]])

# np.abs() 메서드를 사용한 2차원 배열의 절댓값 계산   # 각 원소들의 절댓값을 배열로 반환
print(np.abs(arr1))

[[2 3]
 [3 4]]


In [5]:
# 배열의 올림과 내림

# 2×2 shape의 2차원 배열 생성
arr1 = np.array([[1.423, -3.111],
                 [-4.885, 4.241]])

# 배열의 올림
#
# np.ceil() 메서드를 사용한 배열의 올림 계산    # 각 원소들에 올림한 값을 배열로 반환   # 올림 계산을 하면 소수점이 어떻던 간에 값이 올려진다
print(np.ceil(arr1))

print()

# 배열의 내림 
#
# np.floor() 메서드를 사용한 배열의 내림 계산   # 각 원소들에 내림한 값을 배열로 반환   # 올림 계산을 하면 소수점이 어떻던 간에 값이 내려진다  # 내림 계산 대상이 -3.111과 같이 음수일 때, 내림을 하면 -4가 되는 것을 잘 이해하자. 예전에 배웠던 기억이 난다
print(np.floor(arr1))

[[ 2. -3.]
 [-4.  5.]]

[[ 1. -4.]
 [-5.  4.]]


In [6]:
# 배열의 반올림과 버림

# 2×2 shape의 2차원 배열 생성
arr1 = np.array([[1.423, -3.111],
                 [-4.885, 4.241]])

# 배열의 반올림
#
# np.round() 메서드를 사용한 배열의 반올림 계산    # 각 원소들에 반올림한 값을 배열로 반환
print(np.round(arr1))

print()

# 배열의 버림 
#
# np.trunc() 메서드를 사용한 배열의 버림 계산   # 각 원소들에 버림한 값을 배열로 반환   # 버림 계산을 하면, 소수점이 어떻던 간에 소수점 자리의 수가 버려지고 정수만 남게 된다
print(np.trunc(arr1))

[[ 1. -3.]
 [-5.  4.]]

[[ 1. -3.]
 [-4.  4.]]


>**참조**
>
>인프런 : 데이터 과학을 위한 파이썬 NumPy Basic
>
>https://www.inflearn.com/course/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B3%BC%ED%95%99-%EB%84%98%ED%8C%8C%EC%9D%B4-%EA%B8%B0%EB%B3%B8#