<a href="https://colab.research.google.com/github/yjin0034/TIL-1/blob/master/NumPy_Section_1_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

##Section 1. N차원 배열 생성

1-2. N차원 배열의 데이터 타입

In [11]:
# dtpye : NumPy array의 데이터 타입 지정, 데이터 타입 확인
arr = np.array([1, 2, 3], dtype = np.float64)               # NumPy array의 데이터 타입을 float64 실수형으로 지정
print(arr)                                                  # [1. 2. 3.]

print(arr.dtype)                                            # float64     # NumPy array의 데이터 타입 확인
                                                            # 64 : 메모리에서 몇 비트를 사용할 것인지 나타내는 수

[1. 2. 3.]
float64


In [12]:
arr = np.array([1.1, 2.2, 3.3], dtype = np.int32)           # NumPy array의 데이터 타입을 int32 정수형으로 지정
print(arr)                                                  # [1 2 3] : 실수 부분은 제거되고 정수 부분만 출력

print(arr.dtype)                                            # int32

[1 2 3]
int32


In [13]:
arr = np.array([0, 1, 1], dtype = np.bool_)                 # NumPy array의 데이터 타입을 Boolean 형으로 지정
print(arr)                                                  # [False True True]

print(arr.dtype)                                            # bool

[False  True  True]
bool


In [16]:
# astpye : NumPy array의 데이터 타입 변경
arr = np.array([0, 1, 2, 3])                                
print(arr, arr.dtype)                                       # int64     # NumPy array의 데이터 타입을 따로 지정하지 않으면, NumPy array에 삽입된 데이터에 맞게 자동 지정됨

arr = arr.astype(np.float32)                                # astype으로 NumPy array의 데이터 타입 변경. int64 -> float32
print(arr, arr.dtype)                                       # float32

[0 1 2 3] int64
[0. 1. 2. 3.] float32


In [20]:
# NumPy array에서는 삽입되는 데이터의 조합을 단일 데이터의 조합만 허용
arr = np.array([1, 2, 3.4])                                 # 정수형과 실수형 데이터를 혼합하여 저장하니,
print(arr, arr.dtype)                                       # float64     # NumPy array의 데이터를 float64 실수형으로 데이터 타입을 하나로 맞춰 저장함

arr = np.array([3, 4, "99"])                                # 정수형과 문자형 데이터를 혼합하여 저장하니,
print(arr, arr.dtype)                                       # <U21 : 유니코드 형식     # NumPy array의 데이터를 문자형으로 데이터 타입을 하나로 맞춰 저장함

arr = np.array([3, 4, "문자다"])                            # 정수형과 문자열 데이터를 혼합하여 저장하니,
print(arr, arr.dtype)                                       # <U21 : 유니코드 형식     # NumPy array의 데이터를 문자열로 데이터 타입을 하나로 맞춰 저장함

[1.  2.  3.4] float64
['3' '4' '99'] <U21
['3' '4' '문자다'] <U21


>**참조**
>
>인프런 : 데이터 과학을 위한 파이썬 NumPy Basic
></br>
>https://www.inflearn.com/course/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B3%BC%ED%95%99-%EB%84%98%ED%8C%8C%EC%9D%B4-%EA%B8%B0%EB%B3%B8#