<a href="https://colab.research.google.com/github/yjin0034/TIL-1/blob/master/NumPy_Section_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#Section 1. N차원 배열 생성

##1-1. N차원 배열(ndarray) 생성하기

In [4]:
# 1차원 배열
arr = np.array([1, 2, 3])
print(arr)

print()

# 2차원 배열
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [5]:
# 리스트
type([1, 2, 3])

list

In [6]:
# Numpy Array
type(arr)

numpy.ndarray

In [7]:
# 튜플로 Numpy Array 만들기
tpl = (4, 5, 6)
arr = np.array(tpl)
print(arr)

print()

# 리스트로 Numpy Array 만들기
lst = [1, 2, 3]
arr = np.array(lst)
print(arr)

print()

# 리스트로 2차원 Numpy Array 만들기
lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lst2)
print(arr2)

[4 5 6]

[1 2 3]

[[1 2 3]
 [4 5 6]]


In [13]:
# shape : 배열의 형태(모양) 출력
arr1 =  np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.shape)         # (3, ) : 원소가 3개인 1차원 배열

print(arr2.shape)         # (2, 3) : 2행 3열의 2차원 배열

print()

# ndim : n-dimension, 배열의 차원 출력
print(arr1.ndim)          # 1

print(arr2.ndim)          # 2

print()

# size : 원소의 개수 출력
print(arr1.size)          # 3

print(arr2.size)          # 6

(3,)
(2, 3)

1
2

3
6


>**참조**
>
>인프런 : 데이터 과학을 위한 파이썬 NumPy Basic
></br>
>https://www.inflearn.com/course/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B3%BC%ED%95%99-%EB%84%98%ED%8C%8C%EC%9D%B4-%EA%B8%B0%EB%B3%B8#
