<a href="https://colab.research.google.com/github/yjin0034/TIL-1/blob/master/NumPy_Section_1_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Section 1. N차원 배열 생성

## 1-4. 특정 범위의 값을 가지는 N차원 배열 생성하기

In [3]:
# 리스트의 range()
lst = list(range(0, 10, 3))    # range(start, stop, step)    # 0부터 시작해 10미만까지의 원소를 가지는 리스트 생성하는데, 원소 간 간격을 3으로 설정.
print(lst)

[0, 3, 6, 9]


In [7]:
# NumPy Array의 arange()
arr = np.arange(9)    # 0부터 시작해 9미만까지의 원소를 가지는 NumPy Array을 생성.(start를 지정하지 않으면, 0부터 시작. step을 지정하지 않으면, 1로 지정)
print(arr)

print()

arr = np.arange(2, 15, 2)    # arange(start, stop, step)    # 2부터 시작해 15미만까지의 원소를 가지는 NumPy Array을 생성하는데, 원소 간 간격을 2로 설정.
print(arr)

print()

arr = np.arange(start=2, stop=15, step=2)    # 인자들의 키워드를 직접 입력해 사용할 수도 있다.
print(arr)

[0 1 2 3 4 5 6 7 8]

[ 2  4  6  8 10 12 14]

[ 2  4  6  8 10 12 14]


![image](https://user-images.githubusercontent.com/70255254/169048812-f0dfccae-8181-47b9-889a-097b5f36633c.png)


In [27]:
# linspace() 함수와 logspace() 함수는 특정 곡선을 그리듯 일정 간격으로 구성된 벡터값을 생성하기 위한 함수입니다.
# linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
# logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력


# np.linspace()
# 사용 방법 : np.linspace(a, b, c)
# a와 b사이에 c개의 점(행 벡터)을 생성하기 위한 명령어
# : numpy.linspace(start, end, num=개수, endpoint=True, retstep=False, dtype=자료형)을 사용하여 start ~ end 사이의 값을 개수만큼 생성하여 배열로 반환. 
# (선형 공간에) 생성될 원소의 개수에 따른 각 값의 균등한 등간격으로 분배함.
arr = np.linspace(0, 100, 5)    # 0부터 100까지의 범위 중, 5개의 원소로 균등하게 (선형적으로) 분할한 값들로 구성된 배열 생성. 
print(arr)

print()

arr = np.linspace(0, 100, 250)    # 0부터 100까지의 범위 중, 250개의 원소로 균등하게 (선형적으로) 분할한 값들로 구성된 배열 생성. 
print(arr)

[  0.  25.  50.  75. 100.]

[  0.           0.40160643   0.80321285   1.20481928   1.6064257
   2.00803213   2.40963855   2.81124498   3.21285141   3.61445783
   4.01606426   4.41767068   4.81927711   5.22088353   5.62248996
   6.02409639   6.42570281   6.82730924   7.22891566   7.63052209
   8.03212851   8.43373494   8.83534137   9.23694779   9.63855422
  10.04016064  10.44176707  10.84337349  11.24497992  11.64658635
  12.04819277  12.4497992   12.85140562  13.25301205  13.65461847
  14.0562249   14.45783133  14.85943775  15.26104418  15.6626506
  16.06425703  16.46586345  16.86746988  17.26907631  17.67068273
  18.07228916  18.47389558  18.87550201  19.27710843  19.67871486
  20.08032129  20.48192771  20.88353414  21.28514056  21.68674699
  22.08835341  22.48995984  22.89156627  23.29317269  23.69477912
  24.09638554  24.49799197  24.89959839  25.30120482  25.70281124
  26.10441767  26.5060241   26.90763052  27.30923695  27.71084337
  28.1124498   28.51405622  28.91566265  29.317269

In [29]:
# np.logspace() : 로그 스케일(범위, scale) 값으로 배열을 만드는 함수
# a, b, c 을 log scale 등간격인 행 벡터를 생성하는 명령어. log^a와 log^b 사이에 등간격인 c개의 행 벡터를 생성 -> 이해가 잘 안된다. 퍼온 내용인데, 나중에 다시 보고 수정하자. 내가 봤을 땐, 그냥 base로 설정한 값의 거듭제곱 같다?
# : numpy.logspace(start, end, num=개수, endpoint=True, base=10.0, dtype=자료형)을 사용하여 start ~ end 사이의 로그 배율을 사용하여 값을 개수만큼 생성하여 배열로 반환.
# (로그 공간에) 생성될 원소의 개수에 따른 각 값의 균등한 등간격으로 분배함.
arr = np.logspace(1, 10, 10, base=2)    # 1부터 10까지의 범위 중, 10개의 원소로 균등하게 로그 스케일로 분할한 값들로 구성된 배열 생성. base로 설정한 값의 거듭제곱 같다? 2의 거듭제곱    
print(arr)                              # [2.  4.  8.  16.  32.  64.  128.  256.  512.  1024.]
                                        # 2의 거듭제곱  ->  2^1  2^2  2^3  ~  2^9  2^10
print()

arr = np.logspace(1, 10, 10)    # base를 입력하지 않으면, 기본값인 10으로 설정(base=10)되어 상용 로그 스케일(범위, scale)로 균등하게 분배된다. 10의 거듭제곱
print(arr)                      # [1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
                                # 10의 거듭제곱 -> [10^1  10^2  10^3  ~  10^9  10^10]
print()

arr2 = np.logspace(2, 4, 3)    # 2부터 4까지의 범위 중, 3개의 원소로 균등하게 로그 스케일로 분할한 값들로 구성된 배열 생성. base를 입력하지 않았으므로 상용 로그 스케일로 균등하게 분배
print(arr2)                    # [  100.  1000. 10000.]
                               # 10의 거듭제곱 -> [10^2  10^3  10^4]

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]

[  100.  1000. 10000.]


>**참조**
>
>인프런 : 데이터 과학을 위한 파이썬 NumPy Basic
>
>https://www.inflearn.com/course/%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B3%BC%ED%95%99-%EB%84%98%ED%8C%8C%EC%9D%B4-%EA%B8%B0%EB%B3%B8#